server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: me.xiaoyuu.me.xiaoyuu.myspringcloud.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml


spring:
  application:
    name: me.xiaoyuu.myspringcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: mysqlzxy1126.
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5  #最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: me.xiaoyuu.myspringcloud-dept8001-hystrix #服务名称修改
    prefer-ip-address: true

info:
  app.name: xiaoyuu-me.xiaoyuu.myspringcloud
  company.name: www.xiaoyuu.me
  build.artifactId: $project.artifactId$
  build.version: ${project.version}